@extends('frontend.layouts.master')

@section('meta')
    <!-- Meta description for facebook. -->
    <meta property="og:title" content="{{ $blog->meta_title ?? '' }}"/>
    <meta property="og:description" content="{{ $blog->meta_description ?? '' }}" />
    <meta property="og:image" content="{{ $blog->blog_image ?? '' }}"/>
    <meta property="og:url" content="{{ url()->current() }}"/>

    <!-- Meta description for twitter. -->
    <meta name="twitter:card" content="{{ $blog->blog_image ?? '' }}">
    <meta name="twitter:site" content="{{ url()->current() }}">
    <meta name="twitter:title" content="{{ $blog->meta_title ?? '' }}"/>
    <meta name="twitter:description" content="{{ $blog->meta_description ?? '' }}" />
    <meta name="twitter:image" content="{{ url($blog->blog_image) ?? '' }}" />

    <link rel="canonical" href="{{ $blog->canonical_url }}" />
    <meta name="title" content="{{ $blog->meta_title ?? '' }}"/>
    <meta name="keywords" content="{{ $blog->meta_keywords ?? '' }}"/>
    <meta name="description" content="{{ $blog->meta_description ?? '' }}"/>
@stop

@section('title', $blog->meta_title ?? '')

@push('styles')
    <link rel="stylesheet" href="{{ asset('frontend/css/articles' . ( app()->getLocale() == 'en' ? '.min.css' : '-rtl.min.css') ) }}" crossorigin="anonymous" />
    <link rel="stylesheet" href="{{ asset('frontend/css/faqs.min.css') }}" crossorigin="anonymous" />
@endpush

@push('lang')

    {{-- @if($blog->translate('en')->slug)
    @include('frontend.components.lang_url.lang', ['path' => (app()->getLocale() == 'en' ? '/blog/'.$blog->translate('ar')->slug : '/blog/'.$blog->translate('en')->slug)])
    @else
    @include('frontend.components.lang_url.lang', ['path' => (app()->getLocale() == 'en' ? '/blog/'.$blog->translate('ar')->slug : '/blog/'.$blog->translate('ar')->slug)])
    @endif --}}
    @if($blogLang)
    @include('frontend.components.lang_url.lang', ['path' => ('/blog/'.$blogLang->slug)])
    @elseif($blog->parent)
    @include('frontend.components.lang_url.lang', ['path' => ('/blog/'.$blog->parent->slug)])
    @endif

@endpush

@section('schema_code')
<!--Article Code Generated by https://saijogeorge.com/json-ld-schema-generator/faq/-->
<script type="application/ld+json">
    {
      "@context": "https://schema.org",
      "@type": "NewsArticle",
      "headline": "{{ $blog->title ?? '' }}",
      "image": [
        "{{ $blog->blog_image ?? '' }}"
       ],
      "datePublished": "{{ $blog->created_at ?? '' }}",
      "dateModified": "{{ $blog->updated_at ?? '' }}",
      "author": [{
          "@type": "Organization",
          "name": "Joele Clinics",
          "url": "https://joeleclinics.com"
        }
      ]
    }
</script>
@stop

@section('content')
    <div class="page-header">
        <!-- image -->
        <div class="progress-container">
            <div class="progress-bar" id="myBar"></div>
        </div>
        <div class="page-header__image" data-aos="zoom-out">
            <picture>
                <source srcset="{{ asset('frontend/images/page-header.webp') }}" type="image/webp">
                <img src="{{ asset('frontend/images/page-header.jpg') }}" draggable="false" alt="page header">
            </picture>
        </div>
        <!-- // image -->
        <div class="page-header__text">
            <div class="container">
                <{{ $blog->title_header_optional }} data-aos="fade-up">{{ $blog->title }}</{{ $blog->title_header_optional }}>
                <!-- breadcrumb -->
                <nav aria-label="breadcrumb" data-aos="fade-up" data-aos-delay="50">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{{ route('web.home.index') }}">@lang('system.home')</a></li>
                        <li class="breadcrumb-item"><a href="{{ route('web.blogs.index') }}">@lang('system.blogs')</a></li>
                        <li class="breadcrumb-item active" aria-current="page">{{ $blog->title }}</li>
                    </ol>
                </nav>
                <!-- // breadcrumb -->
            </div>
        </div>
    </div>

    <div class="wrapper blog-details-page">
        <section class="article-details d-pad">
            <div class="container-wrapper full-width-container">
                <div class="row">
                    <div class="col-12 col-lg-3 hidden-mobile">
                        <div class="elms-container side-nav-size sticky-top sticky-side-bar">
                            <nav class="blogs-nav aos-init" data-aos="fade-up">
                                <label class="blogs-nav__title">@lang('system.table_of_contents')</label>
                                @foreach($sections as $keyContent => $sectionContent)
                                    <a class="btn btn-brand-secondary" href="#{{ $keyContent . '_' . $sectionContent->section_slug }}">
                                        {{ $sectionContent->title }}
                                    </a>
                                @endforeach
                            </nav>
                        </div>
                    </div>

                    <div class="col-12 col-xl-6 col-lg-7 elms-container">
                        <!-- title -->
                        <div class="section-title elms-container" data-aos="fade-up">
                            <{{ $blog->title_header_optional }} class="title" data-aos="fade-up">{{ $blog->title }}</{{ $blog->title_header_optional }}>
                            <div class="article-details__info d-flex align-items-center gap-5 flex-wrap" data-aos="fade-up">
                                <span class="color">{{ $blog->category->translate(app()->getLocale())->name }}</span>
                                <small>{{ $blog->created_at->diffForHumans() }}</small>
                            </div>
                        </div>
                        <!-- // title -->
                        <!-- image -->
                        <div class="article-details__image mt-0" data-aos="fade-up">
                            <picture>
                                <source srcset="{{ $blog->blog_image }}" type="image/webp">
                                <img src="{{ $blog->blog_image }}" draggable="false" alt="{{ $blog->alt_image }}">
                            </picture>
                        </div>
                        <!-- // image -->
                         <?php $lang_direction =  app()->getLocale() == 'en' ? 'left' : 'right' ; ?>
                        @foreach($sections as $keySection => $sectionRow)
                            <div id="{{ $keySection . '_' . $sectionRow->section_slug }}" class="article-details__text article-details__text-container" style="background-color:{{ $sectionRow->section_color }}; border-{{$lang_direction}}:solid; border-color:{{ $sectionRow->color_border }}">
                                <{{ $sectionRow->h_optionl }} class="" data-aos="fade-up">{{ $sectionRow->title }}</{{ $sectionRow->h_optionl }}>
                                <p>{!! $sectionRow->content !!}</p>
                            </div>
                        @endforeach
                    </div>

                    @if($blog->doctor_id)
                        <div class="col-12 col-xl-3 col-lg-5 elms-container d-flex justify-content-end">
                        <div id="doctorSideBar" class="doctor__card side-nav-size sticky-top sticky-side-bar">
                            <!-- social -->
                            <div class="doctor__card-social d-flex flex-column gap-2 mt-5">
                                @foreach($blog->doctor->socialMediaData as $key => $doctorLinks)
                                    @if($doctorLinks)
                                        @include("frontend.components.social_media.$key", ['link' => $doctorLinks])
                                    @endif
                                @endforeach
                            </div>
                            <!-- // social -->

                            <a href="{{ route('web.doctors.details', ['slug' => $blog->doctor->slug ]) }}">
                                <label class="blogs-nav__title mt-2">@lang('system.author')</label>
                                <div class="doctor__card-image mt-3">
                                    <picture>
                                        <source class=" lazyloading" srcset="{{ $blog->doctor->doctor_image }}" data-srcset="{{ $blog->doctor->doctor_image }}" type="image/webp">
                                        <img loading="lazy" class=" ls-is-cached lazyloaded" src="{{ $blog->doctor->doctor_image }}" data-src="{{ $blog->doctor->doctor_image }}" alt="{{ $blog->doctor->alt_image ?? $blog->doctor->name }}">
                                    </picture>
                                </div>

                                <h3 class="doctor__card-title h5 text-center">{{ $blog->doctor->name }}</h3>

                                <span class="doctor__card-info d-flex align-items-center justify-content-between gap-4">
                                    <span class="d-block color">{{ $blog->doctor->category->name }}</span>
                                    <span class="d-block">{{ optional($blog->doctor->specializations->first())->name }}</span>
                                </span>
                            </a>

                            <a href="{{url('/doctor/'.$blog->doctor->slug)}}" class="btn btn-brand-gradient w-100">@lang('system.book_now')</a>
                        </div>
                    </div>
                    @endif
                </div>
            </div>
        </section>
    </div>

    @if(count($getQuestions) > 0)
        <div class="related-services d-pad pb-0">
            <div class="container">
                <!-- section title -->
                <div class="section-title text-center" data-aos="fade-up">
                    <h2>@lang('system.frequently_asked_questions')</h2>
                </div>
                <div class="accordion faqs-container" id="accordionExample">
                    @foreach($getQuestions as $key => $question)
                        <div class="accordion-item">
                            <h2 class="accordion-header" id="question_{{ $key }}">
                                <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#question_answer_{{ $key }}" aria-expanded="{{ $key == 0 ? 'true' : 'false' }}" aria-controls="question_answer_{{ $key }}">
                                    <label class="faqs-container__title-container">
                                        {{ $question->question ?? '' }}
                                        <span class="faq__category">{{ $blog->category->name ?? ''}}</span>
                                    </label>
                                </button>
                            </h2>
                            <div id="question_answer_{{ $key }}" class="accordion-collapse collapse {{ $key == 0 ? 'show' : '' }}" aria-labelledby="question_{{ $key }}" data-bs-parent="#accordionExample">
                                <div class="accordion-body">{!! $question->answer ?? '' !!}</div>
                            </div>
                        </div>
                    @endforeach
                </div>
            </div>
        </div>
    @endif

    <div class="d-pad">
        <div class="container">
            <!-- comments -->
            <div class="article-details__text-container">
                <div class="article-details__comments mt-0">
                    <h3 class="h4" data-aos="fade-up">@lang('system.add_your_comment')</h3>
                    <form action="{{ route('web.blog.comment', $blog->id) }}" method="post">
                        @csrf
                        <div class="row">
                        <div class="col-lg-6">
                            <!-- phone -->
                            <div class="mb-3" data-aos="fade-up">
                                <label for="fullName" class="visually-hidden">@lang('system.full_name')</label>
                                <input type="text"
                                    name="name"
                                    class="form-control"
                                    id="fullName"
                                    value="{{ old('name') }}"
                                    placeholder="@lang('system.full_name')" />

                                @error('name')
                                    <span class="text-danger">{{ $message }}</span>
                                @enderror
                            </div>
                            <!-- // phone -->
                            <!-- phone -->
                            <div class="mb-3" data-aos="fade-up">
                                <label for="phoneNumber" class="visually-hidden">@lang('system.phone')</label>
                                <input type="tel"
                                    name="phone"
                                    class="form-control"
                                    id="phoneNumber"
                                    value="{{ old('phone') }}"
                                    placeholder="@lang('system.phone')" />

                                @error('phone')
                                    <span class="text-danger">{{ $message }}</span>
                                @enderror
                            </div>
                            <!-- // phone -->
                        </div>
                        <div class="col-lg-6">
                            <!-- comment -->
                            <div class="mb-3" data-aos="fade-up">
                                <label for="comment" class="visually-hidden">@lang('system.comment')</label>
                                <textarea class="form-control"
                                        id="comment"
                                        name="comment"
                                        placeholder="@lang('system.comment')">{{ old('comment') }}</textarea>

                                @error('comment')
                                    <span class="text-danger">{{ $message }}</span>
                                @enderror
                            </div>
                            <!-- // comment -->
                        </div>
                        <div class="col-lg-12 text-center">
                            <button class="btn btn-brand-gradient" data-aos="fade-up">
                                @lang('system.add_your_comment')
                            </button>
                        </div>
                    </div>
                    </form>
                </div>
                <!-- // comments -->
                @if(count($comments) > 0)
                <div class="article-details__comments">
                    <h3 class="h4 comment__title" data-aos="fade-up">@lang('system.comments')</h3>
                    @foreach($comments as $comment)
                        <!-- comment -->
                        <div class="comment__card card d-flex flex-row gap-4 align-items-start" data-aos="fade-up">
                            <div class="comment__logo">
                                <picture>
                                    <source srcset="{{ asset('frontend/images/icons/user.png') }}" type="image/webp">
                                    <img src="{{ asset('frontend/images/icons/user.png') }}" draggable="false" alt="{{ $comment->name }}" />
                                </picture>
                            </div>
                            <div class="comment__text">
                                <h4 class="h4 comment__title">{{ $comment->name }}</h4>
                                <p class="mb-0">{{ $comment->comment }}</p>
                            </div>
                        </div>
                        <!-- // comment -->
                    @endforeach
                </div>
                @endif
            </div>
        </div>
    </div>

    <div class="container mt-5">
        <div class="row">
            <!-- BEGIN :: related blogs -->
            <div class="section-title text-center" data-aos="fade-up">
                <h2>@lang('system.relatedBlogs')</h2>
            </div>
            <div class="col-12">
                <!-- slider -->
                <div class="articles-slider" data-aos="fade-up">
                    <div class="swiper articlesSlider">
                        <div class="swiper-wrapper">
                            @foreach($relatedBlogs as $relatedBlog)
                                <!-- slide -->
                                <div class="swiper-slide">
                                    <a class="article__card card" href="{{ route('web.blog.show', $relatedBlog->slug) }}">
                                        <div class="article__card-image">
                                            <picture>
                                                <source srcset="{{ $relatedBlog->blog_image }}" type="image/webp">
                                                <img loading="lazy" src="{{ $relatedBlog->blog_image }}" alt="article">
                                            </picture>
                                        </div>
                                        <div class="article__card-text">
                                            <span class="color">{{ $relatedBlog->category->translate(app()->getLocale())->name }}</span>
                                            <h3 class="h5">{{ $relatedBlog->title }}</h3>
                                            <small>{{ $relatedBlog->created_at->diffForHumans() }}</small>
                                        </div>
                                    </a>
                                </div>
                                <!-- // slide -->
                            @endforeach
                        </div>
                        <div class="swiper-pagination"></div>
                        <div class="slider-controls">
                            <div class="swiper-button-next articles-next"></div>
                            <div class="swiper-button-prev articles-prev"></div>
                        </div>
                    </div>
                </div>
                <!-- // slider -->
            </div>
            <!-- END :: related blogs -->
        </div>
    </div>

    <!-- BEGIN :: page header section -->
    {{--<div class="page-header">
        <div class="container">
            <!-- image -->
            <div class="page-header__image">
                <picture>
                    <source srcset="{{ asset('frontend//images/page-header.webp') }}" type="image/webp" />
                    <img src="{{ asset('frontend/images/page-header.png') }}" draggable="false" alt="image" data-aos="zoom-out" />
                </picture>
            </div>
            <!-- // image -->
            <!-- title -->
            <h2 class="h3" data-aos="fade-up" data-aos-delay="100">{{ $blog->name }}</h2>
            <!-- // title -->
        </div>
    </div>--}}
    <!-- END :: page header section -->

    <!-- BEGIN :: page content section -->
    {{--<div class="page-content article brd-top-rad d-pad">
        <div class="container">
            <div class="row">
                <!-- image -->
                <div class="col-lg-6 order-lg-2">
                    <div class="article__page-image">
                        <picture>
                            <source srcset="{{ $blog->image }}" type="image/webp" />
                            <img src="{{ $blog->image }}" alt="{{ $blog->alt_image ?? ''}}" draggable="false" data-aos="zoom-in" />
                        </picture>
                    </div>
                </div>
                <!-- // image -->
                <!-- content -->
                <div class="col-lg-6">
                    <div class="article__content">
                        <div class="article__heading">
                            <span class="color small">{{ $blog->category->name }}</span>
                            <h2 class="h3">{{ $blog->name }}</h2>
                            <span class="small">{{ $blog->created_at->diffForHumans() }}</span>
                        </div>
                        <div class="article__details">
                            {!! $blog->content !!}
                        </div>
                    </div>
                </div>
                <!-- // content -->
            </div>
        </div>
    </div>--}}
    <!-- END :: page content section -->

    <!-- BEGIN :: comments section -->
    {{--<div class="comments">
        <div class="container">
            <form class="form" method="POST" action="{{ route('web.advices.comment', (app()->getLocale() == 'en' ? ['lang' => app()->getLocale()]: '')) }}">
                @csrf

                <div class="row">
                    <div class="col-lg-12">
                        <h3 class="h3" data-aos="fade-up">@lang("messages.Add your Comment")</h3>
                    </div>
                    <!-- block -->
                    <div class="col-lg-6">
                        <div class="comment__block" data-aos="fade-up">

                            @csrf
                            <input type="hidden" name="blog_id" value="{{$blog->id}}">
                            <input type="hidden" name="blog_slug" value="{{$blog->slug}}">
                            <input type="hidden" name="locale" value="{{$app->getLocale()}}">

                            <!-- name -->
                            <div class="form-group row d-flex align-items-center">
                                <label for="commentName" class="col-lg-3 col-form-label">@lang("messages.Full Name")</label>
                                <div class="col-lg-9">
                                    <input type="text"
                                           name="commenter"
                                           class="form-control"
                                           id="commentName"
                                           placeholder="@lang("messages.Full Name")" required />
                                </div>
                            </div>
                            <!-- // name -->
                            <!-- phone -->
                            <div class="form-group row d-flex align-items-center">
                                <label for="commentPhone" class="col-lg-3 col-form-label">@lang("messages.Email Address")</label>
                                <div class="col-lg-9">
                                    <input type="email"
                                           class="form-control"
                                           id="commentPhone"
                                           name="email"
                                           placeholder="@lang("messages.Email Address")" required />
                                </div>
                            </div>
                            <!-- // phone -->
                        </div>
                    </div>
                    <!-- // block -->
                    <!-- block -->
                    <div class="col-lg-6">
                        <div class="comment__block" data-aos="fade-up">
                            <div class="form-group row">
                                <label for="commentName" class="col-lg-3 col-form-label">@lang("messages.Add your Comment")</label>
                                <div class="col-lg-9">
                                    <textarea class="form-control" id="commentMessage" name="content" placeholder="@lang("messages.Add your Comment").." required></textarea>
                                    <button class="btn btn-brand-primary">@lang("messages.Add your Comment")</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- // block -->
                </div>
            </form>
            <!-- comment -->
            <div class="comments-block">
                @foreach($comments as $comment)
                    <!-- comment -->
                    <div class="comment" data-aos="fade-up">
                        <div class="comment__image">
                            <picture>
                                <source srcset="{{ asset('frontend/images/avatar.webp') }}" type="image/webp">
                                <img src="{{ asset('frontend/images/avatar.jpg') }}" alt="avatar">
                            </picture>
                        </div>
                        <div class="comment__text">
                            <h3 class="h6">{{ $comment->commenter }}</h3>
                            <p>{{ $comment->content }}</p>
                        </div>
                    </div>
                    <!-- // comment -->
                @endforeach
            </div>
            <!-- // comment -->
        </div>
    </div>--}}
    <!-- END :: comments section -->

    <!-- related -->
    {{--<div class="related brd-top-rad d-pad">
        <div class="container">
            <h2 class="title" data-aos="fade-up">{{ (app()->getLocale() == 'en') ? 'Related Articles' : 'مقالات ذات صلة'}}</h2>
            <!-- slider -->
            <div class="swiper blogsSlider" data-aos="fade-up">
                <div class="swiper-wrapper">
                    @foreach($relatedArticles as $relatedArticle)
                        <!-- slide -->
                        <div class="swiper-slide">
                            <a href="{{ route('web.advices.details', (app()->getLocale() == 'en' ? ['slug' => $relatedArticle->slug, 'lang' => app()->getLocale()] : ['slug' => $relatedArticle->slug])) }}" class="article">
                                <div class="article__image">
                                    <picture>
                                        <source srcset="{{ $relatedArticle->image }}" type="image/webp" />
                                        <img src="{{ $relatedArticle->image }}" alt="article" draggable="false" />
                                    </picture>
                                </div>
                                <div class="article__text">
                                    <span class="color small">{{ $relatedArticle->category->name }}</span>
                                    <h3 class="h6">{{ $relatedArticle->name }}</h3>
                                    <span class="small">{{ $relatedArticle->created_at->diffForHumans() }}</span>
                                </div>
                            </a>
                        </div>
                        <!-- // slide -->
                    @endforeach
                </div>
                <div class="section-pagination">
                    <div class="blogs-pagination"></div>
                </div>
                <div class="slider-controls">
                    <div class="swiper-button-next blogs-next"></div>
                    <div class="swiper-button-prev blogs-prev"></div>
                </div>
            </div>
            <!-- // slider -->
        </div>
    </div>--}}
    <!-- // related -->

    <!-- book now -->
    {{--<section class="book-now d-pad brd-top-rad" style="background-image: url('{{ asset('frontend/images/book-now.jpg') }}')">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 d-flex align-items-center">
                    <h2 class="h3" data-aos="fade-up">@lang('messages.book_your_appointment_now') <br> @lang('messages.enjoy_unique_treatment_experience')
                    </h2>
                </div>
                <div class="col-lg-6 d-flex align-items-center justify-content-lg-end">
                    <a href="{{ route('web.booking.index', (app()->getLocale() == 'en' ? ['lang' => app()->getLocale()] : '')) }}" class="btn btn-white" data-aos="fade-up">
                        @lang('messages.book_your_appointment_now')
                    </a>
                </div>
            </div>
        </div>
    </section>--}}
    <!-- // book now -->
@stop
