@extends('frontend.layouts.master')

@section('title', __('system.frequently_asked_questions'))

@section('meta')
    {!! $settings['frequently_questions_seo'][app()->getLocale() == 'en'  ?  'en' : 'ar'] ?? '' !!}
@stop

@push('styles')
    <link rel="stylesheet" href="{{ asset('frontend/css/faqs.min.css') }}" crossorigin="anonymous" />
@endpush

@push('lang')
    @include('frontend.components.lang_url.lang', ['path' => '/frequently-questions'])
@endpush

@section('schema_code')
    <!--FAQPage Code Generated by https://saijogeorge.com/json-ld-schema-generator/faq/-->
    <script type="application/ld+json">
        {
          "@context": "https://schema.org",
          "@type": "FAQPage",
          "mainEntity": [
            @foreach($questions as $question)
                {
                  "@type": "Question",
                  "name": "{{ str_replace(["\n\r", "\n", "\r"], '', $question->translate(app()->getLocale())->question) }}",
                  "acceptedAnswer": {
                    "@type": "Answer",
                    "text": "{{ str_replace(["\n\r", "\n", "\r"], '', $question->translate(app()->getLocale())->answer) }}"
                  }
                }
                @if(!$loop->last)
                    ,
                @endif
            @endforeach
          ]
        }
    </script>
@stop

@section('content')
    <!-- BEGIN :: page header section -->
    <div class="page-header">
        <!-- image -->
        <div class="page-header__image" data-aos="zoom-out">
            <picture>
                <source srcset="{{ asset('frontend/images/page-header.webp') }}" type="image/webp">
                <img src="{{ asset('frontend/images/page-header.jpg') }}" draggable="false" alt="page header">
            </picture>
        </div>
        <!-- // image -->
        <div class="page-header__text">
            <div class="container">
                <h2 data-aos="fade-up">@lang('system.frequently_asked_questions')</h2>
                <!-- breadcrumb -->
                <nav aria-label="breadcrumb" data-aos="fade-up" data-aos-delay="50">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{{ route('web.home.index') }}">@lang('system.home')</a></li>
                        <li class="breadcrumb-item active" aria-current="page">@lang('system.frequently_asked_questions')</li>
                    </ol>
                </nav>
                <!-- // breadcrumb -->
            </div>
        </div>
    </div>
    <!-- END :: page header section -->

    <!-- BEGIN :: page content -->
    <div class="wrapper">
        <section class="d-pad">
            <div class="container">
                <!-- section title -->
                <div class="section-title" data-aos="fade-up">
                    <h2>@lang('system.frequently_asked_questions')</h2>
                </div>
                <!-- // section title -->
                <div class="accordion faqs-container" id="accordionExample">
                    @foreach($questions as $key => $question)
                        <div class="accordion-item">
                            <h2 class="accordion-header" id="question_{{ $key }}">
                                <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#question_answer_{{ $key }}" aria-expanded="{{ $key == 0 ? 'true' : 'false' }}" aria-controls="question_answer_{{ $key }}">
                                    <label class="faqs-container__title-container">
                                        {{ $question->translate(app()->getLocale())->question ?? '' }}
                                        <span class="faq__category">{{ $question->category ? $question->category->translate(app()->getLocale())->name ?? '' : '' }}</span>
                                    </label>
                                </button>
                            </h2>
                            <div id="question_answer_{{ $key }}" class="accordion-collapse collapse {{ $key == 0 ? 'show' : '' }}" aria-labelledby="question_{{ $key }}" data-bs-parent="#accordionExample">
                                <div class="accordion-body">{!! $question->translate(app()->getLocale())->answer ?? '' !!}</div>
                            </div>
                        </div>
                    @endforeach
                </div>
            </div>
        </section>
    </div>
    <!-- END :: page content -->
@endsection

@push('js')
    <script type="application/ld+json">
        {
          "@context": "https://schema.org",
          "@type": "VideoObject",
          "name": "Funny Cat Poses 2.0",
          "description": "A short description of your video, we'd keep it at 140 characters just to be safe.",
          "thumbnailUrl": "http://www.example.com/thumbnail.jpg",
          "uploadDate": "2015-04-05T08:00:00+02:00",
          "duration": "PT1M33S",
          "contentUrl": "http://www.example.com/movie.mov",
          "embedUrl": "http://www.example.com/embed?videoetc",
          "interactionCount": "2347"
        }
    </script>
@endpush
